wget    https://api.covid19india.org/csv/latest/raw_data1.csv
wget    https://api.covid19india.org/csv/latest/raw_data2.csv 
wget    https://api.covid19india.org/csv/latest/raw_data3.csv 
wget    https://api.covid19india.org/csv/latest/raw_data4.csv 
wget    https://api.covid19india.org/csv/latest/raw_data5.csv 
wget    https://api.covid19india.org/csv/latest/raw_data6.csv 
wget    https://api.covid19india.org/csv/latest/raw_data7.csv 
wget    https://api.covid19india.org/csv/latest/raw_data8.csv 
wget    https://api.covid19india.org/csv/latest/raw_data9.csv 
wget    https://api.covid19india.org/csv/latest/raw_data10.csv
wget    https://api.covid19india.org/csv/latest/raw_data11.csv
wget    https://api.covid19india.org/csv/latest/raw_data12.csv
wget    https://api.covid19india.org/csv/latest/raw_data13.csv
wget    https://api.covid19india.org/csv/latest/raw_data14.csv
wget    https://api.covid19india.org/csv/latest/raw_data15.csv
wget    https://api.covid19india.org/csv/latest/raw_data16.csv
wget    https://api.covid19india.org/csv/latest/raw_data17.csv
wget    https://api.covid19india.org/csv/latest/raw_data18.csv
wget    https://api.covid19india.org/csv/latest/raw_data19.csv
wget    https://api.covid19india.org/csv/latest/raw_data20.csv
wget    https://api.covid19india.org/csv/latest/raw_data21.csv
wget    https://api.covid19india.org/csv/latest/raw_data22.csv
wget    https://api.covid19india.org/csv/latest/raw_data23.csv
wget    https://api.covid19india.org/csv/latest/raw_data24.csv
wget    https://api.covid19india.org/csv/latest/raw_data25.csv
wget    https://api.covid19india.org/csv/latest/raw_data26.csv
wget    https://api.covid19india.org/csv/latest/raw_data27.csv
wget    https://api.covid19india.org/csv/latest/raw_data28.csv
